
services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports: 
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning
    
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend

  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        # Change the number before : to the port the web interface should be accessible on
        - '5000:80'
        # Change the number before : to the port the SMTP server should be accessible on
        - '25:25'
        # Change the number before : to the port the IMAP server should be accessible on
        - '143:143'
      volumes:
        # This is where smtp4dev stores the database..
          - smtp4dev-data:/smtp4dev
      environment:
        # Uncomment to customise these settings
        #Specifies the URLs the web UI will use inside the container.
        - ServerOptions__Urls=http://*:80

        #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
        - ServerOptions__HostName=smtp4dev

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  worker:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  smtp4dev-data: